# Generated by Django 2.1.2 on 2018-10-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='Imagenes/')),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('raza_predominante', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
    ]
